export const FETCH_COMBINED_COLUMNS_REQUEST = "FETCH_COMBINED_COLUMNS_REQUEST";
export const FETCH_COMBINED_COLUMNS_SUCCESS = "FETCH_COMBINED_COLUMNS_SUCCESS";
export const FETCH_COMBINED_COLUMNS_FAILURE = "FETCH_COMBINED_COLUMNS_FAILURE";
