export const FETCH_USER_CHARTS_DATA_REQUEST = "FETCH_USER_CHARTS_DATA_REQUEST";
export const FETCH_USER_CHARTS_DATA_SUCCESS = "FETCH_USER_CHARTS_DATA_SUCCESS";
export const FETCH_USER_CHARTS_DATA_FAILURE = "FETCH_USER_CHARTS_DATA_FAILURE";
